Pull request for the Association project in the Rails module
guillainbisimwa/Private_Events pull request #1
Opened 2020-11-26 16:26 UTC by jose-Abel

Hello, 

We're requesting the review for the Pull Request of the Association project in the Rails module that consists of creating an application named Private Events that behaves similar to Eventbrite, which allows users to create events and then manage user signups. Users can create events. Events take place at a specific date and at a location. A user can create events. A user can attend many events. An event can be attended by many users.

Hoping to have amazing feedback, happy coding!

2020-11-26 18:35 UTC, lekegitrepo requested changes
## Status: Request changes :recycle:
#### Hi @jose-Abel and @guillainbisimwa :clap: :clap:
#### You have done an incredible job :+1: and also you did a good job for writing such comprehensive tests for the project. However, some of the requirements are missing/not implemented correctly. Check the review summary :point_down: and the inline comments below.

##### Readme:
- **_Improve the instructions in the readme_**

##### Controllers:
- **_Add missing requirements for the action methods_**

##### Database column indexes:
- **_event_id and user_id should be indexed_**

#### Optional:
- **_Try to fix some of the linter errors instead of disabling them. A lot of the rules that are disabled can be easily fixed ( I know fixing linter errors can be frustrating). For example `disable Layout/EndOfLine` I think this is because of the several lines at the end of the code._**

#### _Reviewed by Temitayo Adeleke_

2020-11-26 18:35 UTC, lekegitrepo commented on app/models/event.rb
> +  scope :datetimefuture, -> { where('datetime > ?', DateTime.now) }
- **_[Note] It is a good option to use the requirement specified names: `upcoming`, `previous` (Optional)_**

2020-11-26 18:35 UTC, lekegitrepo commented on app/controllers/events_controller.rb
> +  end
- **_List the past events, i.e. `@past_events = Event.previous_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))_**

- **_List the ucomping events, i.e. `@upcoming_events = Event.upcoming_events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))_**

2020-11-26 18:35 UTC, lekegitrepo commented on app/controllers/users_controller.rb
> +  def show; end
- **_List the events created by user, i.e. `@created_events = current_user.events` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/current_user_show_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))_**

- **_List the events previoulsy attendented by user **using event model scope**, i.e. `@past_events = current_user.attended_events.previous` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))_**

- **_List the upcoming events previously attended by user **using event model scope**, i.e. `@upcoming_events = current_user.attended_events.upcoming` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))_**

2020-11-26 18:35 UTC, lekegitrepo commented on db/schema.rb
> +    t.integer "user_id"
**_Note: Don't edit Schema.rb file directly_**
- **_Both `event_id` and `user_id` columns of the `event_users` table should be indexed_**

2020-11-26 18:35 UTC, lekegitrepo commented on README.md
> +- rails console (or it could be "rails c")
- **_Add instructions on how to install the dependencies, setup and run the project locally_**

2020-11-26 22:22 UTC, blackpintz requested changes
# Status; Changes Required

### Hello team 😄,

**Great job implementing the requested changes 💪. However, there are still a few fixes needed.**

1). **The sign-up requirements are that you create a simple form that only accepts the name or ID of the user. The password is not required, ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/login_requirement.png) from pathwright).**

2). **When I run `rspec spec/system/`, I get the following error:**
![specError](https://user-images.githubusercontent.com/38922385/100394591-be1bb000-304e-11eb-9ee1-4e4d49bb7221.png)

3). **Check more comments below.**

### Happy coding 😃.

**PS: You can reach me on slack (Rose Wanjohi).**

2020-11-26 22:22 UTC, ghost commented on app/models/user.rb
> +  has_many :events, through: :event_users
Line 4 should be defined as `has_many :events, foreign_key: :creator_id`. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_assoc_requirement.png) from odin.

2020-11-26 22:22 UTC, ghost commented on db/schema.rb
> +    t.integer "user_id", null: false
On line 28, It should reference the user using the `creator_id` foreign key instead of `user_id`. Please not this is the `events_table` in `schema.rb`.

2020-11-26 22:22 UTC, ghost commented on app/models/event_user.rb
> +  belongs_to :event
Line two should be written as `belongs_to :attendee, class_name: "User"`.
Line 3 should be written as `belongs_to :attended_event, class_name: "Event"`. See [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/attendee_assoc_requirement.png) from odin.

2020-11-27 17:57 UTC, acushlakoncept approved these changes
# Status: PROJECT APPROVED  🎉 🚀

Hi, @jose-Abel  and @guillainbisimwa congratulations on completing your project and taking the time to implement the changes requested by the TSEs.  

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next project.

Just update the OPTIONAL changes on your readme file.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-11-27 17:57 UTC, acushlakoncept commented on README.md
> +
There isn't a right or wrong rule but looks more conventional to have the **Authors** section just above your **Acknowledgement** section below.

Also, replace Authors with your real names.

2020-11-27 17:59 UTC, merged